### ISSUE TITLE
Adjust workflows

### ISSUE THREAD

**Issue by matmah** [edgefarm/backstage#80]
- Add label to nodepool
```

apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: ${{ nodeName }}
  labels:
    ${{ nodeName }}: ""
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: ${{ nodeName }}
  type: Edge
```

- Remove namespace input from network creation workflow
- Fix label value in application creation workflow: If it is empty, no value is set but it needs to be an empty string
